### ISSUE TITLE
Question: event rollup?

### ISSUE THREAD

**Issue by aehlke** [getsentry/sentry-webhooks#11]
Hi,

We're interested in silencing our backlog of uncaught exceptions, and logging them as metrics. It looks like this might be a way for us to add metrics logging for these silenced exceptions. I can't tell for sure without experimenting with it first - Sentry de-dupes / rolls-up events, is this rollup exposed through this webhook? In other words, will the webhook receiver be able to inherit this knowledge of which group of events each particular event belongs to? (So that, in our use case, it can log the grouped events into the same metric.)

Thanks!

**Comment by aehlke** [comment]
Ah I see this is now built into Sentry. Sorry - hopefully this can be answered re: the latest Sentry rather than this specific extension.

**Comment by dcramer** [comment]
We only send data about groups. It might contain data from an event within it, but you would be able to get accurate counts/etc with webhooks alone.

**Comment by aehlke** [comment]
Perfect - thank you.
